// <auto-generated />
using System;
using ManageMe.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManageMe.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240506001039_AddingViews")]
    partial class AddingViews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChannelRoles", b =>
                {
                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ChannelId", "RoleId");

                    b.HasIndex(new[] { "ChannelId" }, "IX_ChannelRoles_ChannelId");

                    b.HasIndex(new[] { "RoleId" }, "IX_ChannelRoles_RoleId");

                    b.ToTable("ChannelRoles", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Activity__3214EC07383AA6F9");

                    b.HasIndex(new[] { "Name" }, "UQ__Activity__737584F6143B801E")
                        .IsUnique();

                    b.ToTable("Activity", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("EnrollmentYear")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("Salary")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("WorkHours")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D10534956297FA")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex(new[] { "GroupId" }, "index_User_Group");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessTypeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("ChannelPic")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JoinCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Channel__3214EC07E13C7935");

                    b.HasIndex(new[] { "SubjectId" }, "index_Channel_Subject");

                    b.ToTable("Channel", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.ChannelRequest", b =>
                {
                    b.Property<string>("RequesterId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("RequesterId", "ChannelId");

                    b.HasIndex("ChannelId");

                    b.ToTable("ChannelRequests");
                });

            modelBuilder.Entity("ManageMe.Entities.ChannelUser", b =>
                {
                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsModerator")
                        .HasColumnType("bit");

                    b.HasKey("ChannelId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ChannelUsers");
                });

            modelBuilder.Entity("ManageMe.Entities.Degree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<decimal?>("FinalGrade")
                        .HasColumnType("decimal(7, 5)");

                    b.Property<string>("GuidingTeacherId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Thesis")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Degree__3214EC07A242F3CD");

                    b.HasIndex(new[] { "Thesis" }, "UQ__Degree__9B78415BCA0B6C85")
                        .IsUnique();

                    b.HasIndex(new[] { "GuidingTeacherId" }, "index_Degree_GuidingTeacher");

                    b.HasIndex(new[] { "StudentId" }, "index_Degree_Student");

                    b.ToTable("Degree", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.Entities.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsForOlympiadParticipants")
                        .HasColumnType("bit");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudyDomainId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "StudyDomainId" }, "IX_Batch_StudyDomain");

                    b.ToTable("Batch", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.Entities.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Building", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.Entities.FinalGrade", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "SubjectId");

                    b.HasIndex(new[] { "StudentId" }, "IX_FinalGrade_Student");

                    b.HasIndex(new[] { "SubjectId" }, "IX_FinalGrade_Subject");

                    b.ToTable("FinalGrade", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.Entities.GradingCriterion", b =>
                {
                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("GradingActivityId")
                        .HasColumnType("int");

                    b.Property<bool>("MattersForPassingTheSubject")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MinimumPointsRequired")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<decimal?>("Points")
                        .HasColumnType("decimal(4, 2)");

                    b.HasKey("SubjectId", "GroupId", "GradingActivityId")
                        .HasName("PK_GradingCriterion");

                    b.HasIndex(new[] { "GradingActivityId" }, "index_GradingCriterion_GradingActivity");

                    b.HasIndex(new[] { "GroupId" }, "index_GradingCriterion_Group");

                    b.HasIndex(new[] { "SubjectId" }, "index_GradingCriterion_Subject");

                    b.ToTable("GradingCriterion", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.Entities.GradingCriterionSubject", b =>
                {
                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<decimal?>("BonusPoints")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<bool>("BonusPointsMattersForPassingSubject")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MinimumPointsRequired")
                        .HasColumnType("decimal(4, 2)");

                    b.HasKey("SubjectId", "GroupId")
                        .HasName("PK_GradingCriterionSubject");

                    b.HasIndex(new[] { "GroupId" }, "index_GradingCriterionSubject_Group");

                    b.HasIndex(new[] { "SubjectId" }, "index_GradingCriterionSubject_Subject");

                    b.ToTable("GradingCriterionSubject", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.Entities.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalLetter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<bool>("HasComputers")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BuildingId" }, "IX_Hall_Building");

                    b.ToTable("Hall", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.Entities.Schedule", b =>
                {
                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("HallId")
                        .HasColumnType("int");

                    b.Property<int>("ActivityFrequencyId")
                        .HasColumnType("int");

                    b.Property<int>("DistributionId")
                        .HasColumnType("int");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("Hour")
                        .HasColumnType("int");

                    b.Property<int>("Minute")
                        .HasColumnType("int");

                    b.HasKey("SubjectId", "TeacherId", "ActivityId", "GroupId", "HallId", "ActivityFrequencyId", "DistributionId");

                    b.HasIndex(new[] { "ActivityId" }, "IX_Schedule_Activity");

                    b.HasIndex(new[] { "GroupId" }, "IX_Schedule_Group");

                    b.HasIndex(new[] { "HallId" }, "IX_Schedule_Hall");

                    b.HasIndex(new[] { "SubjectId" }, "IX_Schedule_Subject");

                    b.HasIndex(new[] { "TeacherId" }, "IX_Schedule_Teacher");

                    b.ToTable("Schedule", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.Entities.SubjectActivityFrequency", b =>
                {
                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("StudyDomainId")
                        .HasColumnType("int");

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectActivityFrequencyId")
                        .HasColumnType("int");

                    b.HasKey("SubjectId", "StudyDomainId", "ActivityId")
                        .HasName("PK_SubjectActivityFrequency");

                    b.HasIndex("StudyDomainId", "SubjectId");

                    b.HasIndex(new[] { "ActivityId" }, "index_SubjectActivityFrequency_Activity");

                    b.HasIndex(new[] { "StudyDomainId" }, "index_SubjectActivityFrequency_StudyDomain");

                    b.HasIndex(new[] { "SubjectId" }, "index_SubjectActivityFrequency_Subject");

                    b.ToTable("SubjectActivityFrequency", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.Entities.TeacherPermission", b =>
                {
                    b.Property<string>("TeacherId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.HasKey("TeacherId", "SubjectId", "ActivityId");

                    b.HasIndex(new[] { "ActivityId" }, "index_TeacherPermission_Activity");

                    b.HasIndex(new[] { "SubjectId" }, "index_TeacherPermission_Subject");

                    b.HasIndex(new[] { "TeacherId" }, "index_TeacherPermission_Teacher");

                    b.ToTable("TeacherPermission", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.Entities.UniversitaryYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FirstSemesterEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FirstSemesterStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SecondSemesterEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SecondSemesterStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UniversitaryYears");
                });

            modelBuilder.Entity("ManageMe.Entities.Entities.VwScheduleColor", b =>
                {
                    b.Property<int>("ActivityFrequencyId")
                        .HasColumnType("int");

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("DistributionId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("HallId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("VwScheduleColor", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.Entities.VwStudentGradeForSubject", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GradingActivityId")
                        .HasColumnType("int");

                    b.Property<bool>("GradingActivityPassed")
                        .HasColumnType("bit");

                    b.Property<decimal>("GradingActivityTotalPoints")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPoints")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalPointsRounded")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("VwStudentGradeForSubject", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.Entities.VwTeacherGroupSubjectActivities", b =>
                {
                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ActivityTypeId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("VwTeacherGroupSubjectActivities", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("UniversitaryYearId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Event__3214EC078E412436");

                    b.HasIndex(new[] { "Name" }, "UQ__Event__737584F62DE15053")
                        .IsUnique();

                    b.HasIndex(new[] { "UniversitaryYearId" }, "index_Event_UniversitaryYear");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ExamTypeId")
                        .HasColumnType("int");

                    b.Property<int>("HallId")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__Exam__3214EC078C26998E");

                    b.HasIndex(new[] { "AuthorId" }, "index_Exam_Author");

                    b.HasIndex(new[] { "ExamTypeId" }, "index_Exam_ExamType");

                    b.HasIndex(new[] { "HallId" }, "index_Exam_Hall");

                    b.HasIndex(new[] { "SessionId" }, "index_Exam_Session");

                    b.HasIndex(new[] { "SubjectId" }, "index_Exam_Subject");

                    b.ToTable("Exam", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.Grade", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("GradingActivityId")
                        .HasColumnType("int");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(4, 2)");

                    b.HasKey("StudentId", "SubjectId", "GradingActivityId", "WeekNumber");

                    b.HasIndex(new[] { "GradingActivityId" }, "index_Grade_GradingActivity");

                    b.HasIndex(new[] { "StudentId" }, "index_Grade_Student");

                    b.HasIndex(new[] { "SubjectId" }, "index_Grade_Subject");

                    b.ToTable("Grade", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.GradingActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id")
                        .HasName("PK_GradingActivity");

                    b.HasIndex(new[] { "Name" }, "UQ_GradingActivity")
                        .IsUnique();

                    b.HasIndex(new[] { "ActivityId" }, "index_GradingActivity_Activity");

                    b.ToTable("GradingActivity", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Group__3214EC07AA267893");

                    b.HasIndex(new[] { "Number" }, "UQ__Group__78A1A19D3536E801")
                        .IsUnique();

                    b.HasIndex(new[] { "BatchId" }, "index_Group_Batch");

                    b.ToTable("Group", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.Homework", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Homework__3214EC07CE060F46");

                    b.HasIndex(new[] { "AuthorId" }, "index_Homework_Author");

                    b.HasIndex(new[] { "SubjectId" }, "index_Homework_Subject");

                    b.ToTable("Homework", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK__Invitation__3214EC178C26998E");

                    b.HasIndex(new[] { "ChannelId" }, "index_Invitation_Channel");

                    b.HasIndex(new[] { "ReceiverId" }, "index_Invitation_Receiver");

                    b.HasIndex(new[] { "SenderId" }, "index_Invitation_Sender");

                    b.ToTable("Invitation", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ChannelId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsAnnouncement")
                        .HasColumnType("bit");

                    b.Property<int>("MessageTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentMessageId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Message__3214EC07E325146B");

                    b.HasIndex("ChannelId");

                    b.HasIndex(new[] { "AuthorId" }, "index_Message_Author");

                    b.HasIndex(new[] { "MessageTypeId" }, "index_Message_MessageType");

                    b.HasIndex(new[] { "ParentMessageId" }, "index_Message_ParentMessage");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.Methodology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id")
                        .HasName("PK__Methodol__3214EC07D38F9247");

                    b.HasIndex(new[] { "Name" }, "UQ__Methodol__737584F68D2AB986")
                        .IsUnique();

                    b.ToTable("Methodology", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.NumeFamilie", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Nume")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__NumeFami__3214EC27F4163969");

                    b.ToTable("NumeFamilie", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.Prenume", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Prenume1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Prenume");

                    b.HasKey("Id")
                        .HasName("PK__Prenume__3214EC27B7AC0E5B");

                    b.ToTable("Prenume", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsAproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<bool?>("IsDeclined")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<bool?>("IsPending")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("RequesterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SolverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("ThemeId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Request__3214EC07F5F33126");

                    b.HasIndex(new[] { "RequesterId" }, "index_Request_Requester");

                    b.HasIndex(new[] { "SolverId" }, "index_Request_Solver");

                    b.HasIndex(new[] { "ThemeId" }, "index_Request_Theme");

                    b.ToTable("Request", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("SessionTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("UniversitaryYearId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Session__3214EC07361FB95C");

                    b.HasIndex(new[] { "SessionTypeId" }, "index_Session_SessionType");

                    b.HasIndex(new[] { "UniversitaryYearId" }, "index_Session_UniversitaryYear");

                    b.ToTable("Session", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.StudyDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StudyYears")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StudyDom__3214EC07F9B105B0");

                    b.HasIndex(new[] { "Name" }, "UQ__StudyDom__737584F6CE28CABC")
                        .IsUnique();

                    b.ToTable("StudyDomain", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.StudyPlan", b =>
                {
                    b.Property<int>("StudyDomainId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("CourseCredits")
                        .HasColumnType("int");

                    b.Property<int>("EvaluationForm")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.Property<int>("LaboratoryCredits")
                        .HasColumnType("int");

                    b.Property<int>("ProjectCredits")
                        .HasColumnType("int");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<int>("SeminaryCredits")
                        .HasColumnType("int");

                    b.Property<int>("SubjectType")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("TotalCredits")
                        .HasColumnType("int");

                    b.HasKey("StudyDomainId", "SubjectId");

                    b.HasIndex(new[] { "StudyDomainId" }, "index_StudyPlan_StudyDomain");

                    b.HasIndex(new[] { "SubjectId" }, "index_StudyPlan_Subject");

                    b.ToTable("StudyPlan", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Subject__3214EC07E8D1AEAB");

                    b.HasIndex(new[] { "Name" }, "UQ__Subject__737584F63299DB1E")
                        .IsUnique();

                    b.ToTable("Subject", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id")
                        .HasName("PK__Theme__3214EC07737EACA1");

                    b.HasIndex(new[] { "Name" }, "UQ__Theme__737584F667099D1F")
                        .IsUnique();

                    b.ToTable("Theme", (string)null);
                });

            modelBuilder.Entity("MethodologyTheme", b =>
                {
                    b.Property<int>("MethodologyId")
                        .HasColumnType("int");

                    b.Property<int>("ThemeId")
                        .HasColumnType("int");

                    b.HasKey("MethodologyId", "ThemeId");

                    b.HasIndex(new[] { "MethodologyId" }, "index_MethodologyTheme_Methodology");

                    b.HasIndex(new[] { "ThemeId" }, "index_MethodologyTheme_Theme");

                    b.ToTable("MethodologyTheme", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TeacherPermissionGroup", b =>
                {
                    b.Property<string>("TeacherId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("TeacherId", "ActivityId", "SubjectId", "GroupId");

                    b.HasIndex("TeacherId", "SubjectId", "ActivityId");

                    b.HasIndex(new[] { "ActivityId" }, "IX_TeacherPermissionGroup_ActivityId");

                    b.HasIndex(new[] { "GroupId" }, "IX_TeacherPermissionGroup_GroupId");

                    b.HasIndex(new[] { "SubjectId" }, "IX_TeacherPermissionGroup_SubjectId");

                    b.HasIndex(new[] { "TeacherId" }, "IX_TeacherPermissionGroup_TeacherId");

                    b.ToTable("TeacherPermissionGroup", (string)null);
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "RoleId" }, "index_UserRole_Role");

                    b.HasIndex(new[] { "UserId" }, "index_UserRole_User");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("ManageMe.Entities.ApplicationRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.HasIndex(new[] { "Name" }, "UQ__Role__737584F66C18D99F")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("ChannelRoles", b =>
                {
                    b.HasOne("ManageMe.Entities.Channel", null)
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .IsRequired()
                        .HasConstraintName("FK_ChannelRoles_Channel_ChannelId");

                    b.HasOne("ManageMe.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_ChannelRoles_Role_RoleId");
                });

            modelBuilder.Entity("ManageMe.Entities.ApplicationUser", b =>
                {
                    b.HasOne("ManageMe.Entities.Group", "Group")
                        .WithMany("Users")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("FK__User__GroupId__02925FBF");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("ManageMe.Entities.Channel", b =>
                {
                    b.HasOne("ManageMe.Entities.Subject", "Subject")
                        .WithMany("Channels")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK__Channel__Subject__361203C5");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ManageMe.Entities.ChannelRequest", b =>
                {
                    b.HasOne("ManageMe.Entities.Channel", "Channel")
                        .WithMany("ChannelRequests")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManageMe.Entities.ApplicationUser", "Requester")
                        .WithMany("ChannelRequests")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("ManageMe.Entities.ChannelUser", b =>
                {
                    b.HasOne("ManageMe.Entities.Channel", "Channel")
                        .WithMany("ChannelUsers")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManageMe.Entities.ApplicationUser", "User")
                        .WithMany("ChannelUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ManageMe.Entities.Degree", b =>
                {
                    b.HasOne("ManageMe.Entities.ApplicationUser", "GuidingTeacher")
                        .WithMany("DegreeGuidingTeachers")
                        .HasForeignKey("GuidingTeacherId")
                        .IsRequired()
                        .HasConstraintName("FK__Degree__GuidingT__53A266AC");

                    b.HasOne("ManageMe.Entities.ApplicationUser", "Student")
                        .WithMany("DegreeStudents")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Degree__StudentI__52AE4273");

                    b.Navigation("GuidingTeacher");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ManageMe.Entities.Entities.Batch", b =>
                {
                    b.HasOne("ManageMe.Entities.StudyDomain", "StudyDomain")
                        .WithMany("Batches")
                        .HasForeignKey("StudyDomainId")
                        .IsRequired()
                        .HasConstraintName("FK_Batch_StudyDomain");

                    b.Navigation("StudyDomain");
                });

            modelBuilder.Entity("ManageMe.Entities.Entities.FinalGrade", b =>
                {
                    b.HasOne("ManageMe.Entities.ApplicationUser", "Student")
                        .WithMany("FinalGrades")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_FinalGrade_Student");

                    b.HasOne("ManageMe.Entities.Subject", "Subject")
                        .WithMany("FinalGrades")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_FinalGrade_Subject");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ManageMe.Entities.Entities.GradingCriterion", b =>
                {
                    b.HasOne("ManageMe.Entities.GradingActivity", "GradingActivity")
                        .WithMany("GradingCriteria")
                        .HasForeignKey("GradingActivityId")
                        .IsRequired()
                        .HasConstraintName("FK_GradingCriterion_GradingActivity");

                    b.HasOne("ManageMe.Entities.Group", "Group")
                        .WithMany("GradingCriteria")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK_GradingCriterion_Group");

                    b.HasOne("ManageMe.Entities.Subject", "Subject")
                        .WithMany("GradingCriteria")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_GradingCriterion_Subject");

                    b.Navigation("GradingActivity");

                    b.Navigation("Group");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ManageMe.Entities.Entities.GradingCriterionSubject", b =>
                {
                    b.HasOne("ManageMe.Entities.Group", "Group")
                        .WithMany("GradingCriterionSubjects")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK_GradingCriterionSubject_Group");

                    b.HasOne("ManageMe.Entities.Subject", "Subject")
                        .WithMany("GradingCriterionSubjects")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_GradingCriterionSubject_Subject");

                    b.Navigation("Group");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ManageMe.Entities.Entities.Hall", b =>
                {
                    b.HasOne("ManageMe.Entities.Entities.Building", "Building")
                        .WithMany("Halls")
                        .HasForeignKey("BuildingId")
                        .IsRequired()
                        .HasConstraintName("FK_Hall_Building");

                    b.Navigation("Building");
                });

            modelBuilder.Entity("ManageMe.Entities.Entities.Schedule", b =>
                {
                    b.HasOne("ManageMe.Entities.Activity", "Activity")
                        .WithMany("Schedules")
                        .HasForeignKey("ActivityId")
                        .IsRequired()
                        .HasConstraintName("FK_Schedule_Activity");

                    b.HasOne("ManageMe.Entities.Group", "Group")
                        .WithMany("Schedules")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK_Schedule_Group");

                    b.HasOne("ManageMe.Entities.Entities.Hall", "Hall")
                        .WithMany("Schedules")
                        .HasForeignKey("HallId")
                        .IsRequired()
                        .HasConstraintName("FK_Schedule_Hall");

                    b.HasOne("ManageMe.Entities.Subject", "Subject")
                        .WithMany("Schedules")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Schedule_Subject");

                    b.HasOne("ManageMe.Entities.ApplicationUser", "Teacher")
                        .WithMany("Schedules")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK_Schedule_Teacher");

                    b.Navigation("Activity");

                    b.Navigation("Group");

                    b.Navigation("Hall");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ManageMe.Entities.Entities.SubjectActivityFrequency", b =>
                {
                    b.HasOne("ManageMe.Entities.Activity", "Activity")
                        .WithMany("SubjectActivityFrequencies")
                        .HasForeignKey("ActivityId")
                        .IsRequired()
                        .HasConstraintName("FK_SubjectActivityFrequency_Activity");

                    b.HasOne("ManageMe.Entities.StudyPlan", "StudyPlan")
                        .WithMany("SubjectActivityFrequencies")
                        .HasForeignKey("StudyDomainId", "SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_SubjectActivityFrequency_StudyPlan");

                    b.Navigation("Activity");

                    b.Navigation("StudyPlan");
                });

            modelBuilder.Entity("ManageMe.Entities.Entities.TeacherPermission", b =>
                {
                    b.HasOne("ManageMe.Entities.Activity", "Activity")
                        .WithMany("TeacherPermissions")
                        .HasForeignKey("ActivityId")
                        .IsRequired()
                        .HasConstraintName("FK_TeacherPermission_Activity");

                    b.HasOne("ManageMe.Entities.Subject", "Subject")
                        .WithMany("TeacherPermissions")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_TeacherPermission_Subject");

                    b.HasOne("ManageMe.Entities.ApplicationUser", "Teacher")
                        .WithMany("TeacherPermissions")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK_TeacherPermission_Teacher");

                    b.Navigation("Activity");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ManageMe.Entities.Event", b =>
                {
                    b.HasOne("ManageMe.Entities.Entities.UniversitaryYear", "UniversitaryYear")
                        .WithMany("Events")
                        .HasForeignKey("UniversitaryYearId")
                        .IsRequired()
                        .HasConstraintName("FK__Event__UniversitaryYear__2116E6DF");

                    b.Navigation("UniversitaryYear");
                });

            modelBuilder.Entity("ManageMe.Entities.Exam", b =>
                {
                    b.HasOne("ManageMe.Entities.ApplicationUser", "Author")
                        .WithMany("Exams")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK__Exam__AuthorId__2D7CBDC4");

                    b.HasOne("ManageMe.Entities.Entities.Hall", "Hall")
                        .WithMany("Exams")
                        .HasForeignKey("HallId")
                        .IsRequired()
                        .HasConstraintName("FK__Exam__HallId__2A4B4B5E");

                    b.HasOne("ManageMe.Entities.Session", "Session")
                        .WithMany("Exams")
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("FK__Exam__SessionId__2B947552");

                    b.HasOne("ManageMe.Entities.Subject", "Subject")
                        .WithMany("Exams")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK__Exam__SubjectId__2C88998B");

                    b.Navigation("Author");

                    b.Navigation("Hall");

                    b.Navigation("Session");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ManageMe.Entities.Grade", b =>
                {
                    b.HasOne("ManageMe.Entities.GradingActivity", "GradingActivity")
                        .WithMany("Grades")
                        .HasForeignKey("GradingActivityId")
                        .IsRequired()
                        .HasConstraintName("FK_Grade_GradingActivity");

                    b.HasOne("ManageMe.Entities.ApplicationUser", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Grade_Student");

                    b.HasOne("ManageMe.Entities.Subject", "Subject")
                        .WithMany("Grades")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Grade_Subject");

                    b.Navigation("GradingActivity");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ManageMe.Entities.GradingActivity", b =>
                {
                    b.HasOne("ManageMe.Entities.Activity", "Activity")
                        .WithMany("GradingActivities")
                        .HasForeignKey("ActivityId")
                        .IsRequired()
                        .HasConstraintName("FK_GradingActivity_Activity");

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("ManageMe.Entities.Group", b =>
                {
                    b.HasOne("ManageMe.Entities.Entities.Batch", "Batch")
                        .WithMany("Groups")
                        .HasForeignKey("BatchId")
                        .IsRequired()
                        .HasConstraintName("FK__Group__Batch__7BE56230");

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("ManageMe.Entities.Homework", b =>
                {
                    b.HasOne("ManageMe.Entities.ApplicationUser", "Author")
                        .WithMany("Homeworks")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK__Homework__Author__3335971A");

                    b.HasOne("ManageMe.Entities.Subject", "Subject")
                        .WithMany("Homeworks")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK__Homework__Subjec__324172E1");

                    b.Navigation("Author");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ManageMe.Entities.Invitation", b =>
                {
                    b.HasOne("ManageMe.Entities.Channel", "Channel")
                        .WithMany("Invitations")
                        .HasForeignKey("ChannelId")
                        .IsRequired()
                        .HasConstraintName("FK__Invitation__ChannelId__5B947552");

                    b.HasOne("ManageMe.Entities.ApplicationUser", "Receiver")
                        .WithMany("ReceivedInvitations")
                        .HasForeignKey("ReceiverId")
                        .IsRequired()
                        .HasConstraintName("FK__Invitation__ReceiverId__4D7CBDC4");

                    b.HasOne("ManageMe.Entities.ApplicationUser", "Sender")
                        .WithMany("SentInvitations")
                        .HasForeignKey("SenderId")
                        .IsRequired()
                        .HasConstraintName("FK__Invitation__SenderId__3D7CBDC4");

                    b.Navigation("Channel");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("ManageMe.Entities.Message", b =>
                {
                    b.HasOne("ManageMe.Entities.ApplicationUser", "Author")
                        .WithMany("Messages")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK__Message__AuthorI__3EA749C6");

                    b.HasOne("ManageMe.Entities.Channel", "Channel")
                        .WithMany("Messages")
                        .HasForeignKey("ChannelId");

                    b.HasOne("ManageMe.Entities.Message", "ParentMessage")
                        .WithMany("ChildrenMessages")
                        .HasForeignKey("ParentMessageId")
                        .HasConstraintName("FK__Message__ParentM__3CBF0154");

                    b.Navigation("Author");

                    b.Navigation("Channel");

                    b.Navigation("ParentMessage");
                });

            modelBuilder.Entity("ManageMe.Entities.Request", b =>
                {
                    b.HasOne("ManageMe.Entities.ApplicationUser", "Requester")
                        .WithMany("RequestRequesters")
                        .HasForeignKey("RequesterId")
                        .IsRequired()
                        .HasConstraintName("FK__Request__Request__4A18FC72");

                    b.HasOne("ManageMe.Entities.ApplicationUser", "Solver")
                        .WithMany("RequestSolvers")
                        .HasForeignKey("SolverId")
                        .IsRequired()
                        .HasConstraintName("FK__Request__SolverI__4EDDB18F");

                    b.HasOne("ManageMe.Entities.Theme", "Theme")
                        .WithMany("Requests")
                        .HasForeignKey("ThemeId")
                        .IsRequired()
                        .HasConstraintName("FK__Request__ThemeId__4B0D20AB");

                    b.Navigation("Requester");

                    b.Navigation("Solver");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("ManageMe.Entities.Session", b =>
                {
                    b.HasOne("ManageMe.Entities.Entities.UniversitaryYear", "UniversitaryYear")
                        .WithMany("Sessions")
                        .HasForeignKey("UniversitaryYearId")
                        .IsRequired()
                        .HasConstraintName("FK__Session__UniversitaryYear__25DB9BFC");

                    b.Navigation("UniversitaryYear");
                });

            modelBuilder.Entity("ManageMe.Entities.StudyPlan", b =>
                {
                    b.HasOne("ManageMe.Entities.StudyDomain", "StudyDomain")
                        .WithMany("StudyPlans")
                        .HasForeignKey("StudyDomainId")
                        .IsRequired()
                        .HasConstraintName("FK_StudyPlan_StudyDomain");

                    b.HasOne("ManageMe.Entities.Subject", "Subject")
                        .WithMany("StudyPlans")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_StudyPlan_Subject");

                    b.Navigation("StudyDomain");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("MethodologyTheme", b =>
                {
                    b.HasOne("ManageMe.Entities.Methodology", null)
                        .WithMany()
                        .HasForeignKey("MethodologyId")
                        .IsRequired()
                        .HasConstraintName("FK_MethodologyTheme_Methodology");

                    b.HasOne("ManageMe.Entities.Theme", null)
                        .WithMany()
                        .HasForeignKey("ThemeId")
                        .IsRequired()
                        .HasConstraintName("FK_MethodologyTheme_Theme");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ManageMe.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ManageMe.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManageMe.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ManageMe.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeacherPermissionGroup", b =>
                {
                    b.HasOne("ManageMe.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK_TeacherPermissionGroup_Group");

                    b.HasOne("ManageMe.Entities.Entities.TeacherPermission", null)
                        .WithMany()
                        .HasForeignKey("TeacherId", "SubjectId", "ActivityId")
                        .IsRequired()
                        .HasConstraintName("FK_TeacherPermissionGroup_TeacherPermission");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.HasOne("ManageMe.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_Role");

                    b.HasOne("ManageMe.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_User");
                });

            modelBuilder.Entity("ManageMe.Entities.ApplicationRole", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithOne()
                        .HasForeignKey("ManageMe.Entities.ApplicationRole", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ManageMe.Entities.Activity", b =>
                {
                    b.Navigation("GradingActivities");

                    b.Navigation("Schedules");

                    b.Navigation("SubjectActivityFrequencies");

                    b.Navigation("TeacherPermissions");
                });

            modelBuilder.Entity("ManageMe.Entities.ApplicationUser", b =>
                {
                    b.Navigation("ChannelRequests");

                    b.Navigation("ChannelUsers");

                    b.Navigation("DegreeGuidingTeachers");

                    b.Navigation("DegreeStudents");

                    b.Navigation("Exams");

                    b.Navigation("FinalGrades");

                    b.Navigation("Grades");

                    b.Navigation("Homeworks");

                    b.Navigation("Messages");

                    b.Navigation("ReceivedInvitations");

                    b.Navigation("RequestRequesters");

                    b.Navigation("RequestSolvers");

                    b.Navigation("Schedules");

                    b.Navigation("SentInvitations");

                    b.Navigation("TeacherPermissions");
                });

            modelBuilder.Entity("ManageMe.Entities.Channel", b =>
                {
                    b.Navigation("ChannelRequests");

                    b.Navigation("ChannelUsers");

                    b.Navigation("Invitations");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("ManageMe.Entities.Entities.Batch", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("ManageMe.Entities.Entities.Building", b =>
                {
                    b.Navigation("Halls");
                });

            modelBuilder.Entity("ManageMe.Entities.Entities.Hall", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("ManageMe.Entities.Entities.UniversitaryYear", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("ManageMe.Entities.GradingActivity", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("GradingCriteria");
                });

            modelBuilder.Entity("ManageMe.Entities.Group", b =>
                {
                    b.Navigation("GradingCriteria");

                    b.Navigation("GradingCriterionSubjects");

                    b.Navigation("Schedules");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ManageMe.Entities.Message", b =>
                {
                    b.Navigation("ChildrenMessages");
                });

            modelBuilder.Entity("ManageMe.Entities.Session", b =>
                {
                    b.Navigation("Exams");
                });

            modelBuilder.Entity("ManageMe.Entities.StudyDomain", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("StudyPlans");
                });

            modelBuilder.Entity("ManageMe.Entities.StudyPlan", b =>
                {
                    b.Navigation("SubjectActivityFrequencies");
                });

            modelBuilder.Entity("ManageMe.Entities.Subject", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("Exams");

                    b.Navigation("FinalGrades");

                    b.Navigation("Grades");

                    b.Navigation("GradingCriteria");

                    b.Navigation("GradingCriterionSubjects");

                    b.Navigation("Homeworks");

                    b.Navigation("Schedules");

                    b.Navigation("StudyPlans");

                    b.Navigation("TeacherPermissions");
                });

            modelBuilder.Entity("ManageMe.Entities.Theme", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
